
spring:
    cloud:
        nacos:
            discovery:
                server-addr: '101.37.29.47:6399'
                heart-beat-timeout: 10000
application:
    name: problem-warehouse
server:
    port: 8081